import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/navbar/navbar";
import Modal from "./components/modals/Modal";
import LoginModal from "./components/modals/LoginModal";
import SignupModal from "./components/modals/SignupModal";
import AddPropertyModal from "./components/modals/AddPropertyModal";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Nextbnb",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    const content = (
        <div>
            <p>Some content</p>
        </div>
    );
    return (
        <html lang="en">
            <body className={inter.className}>
                <Navbar />
                <div className=" pt-2">{children}</div>
                {/* <Modal label="modal test" content={content} isOpen={true} /> */}
                <LoginModal />
                <SignupModal />
                <AddPropertyModal />
            </body>
        </html>
    );
}
